// SayHello.idl
//
// Dinh nghia interface ISayHello + coclass SayHelloServer.
// Attribute [oleautomation] bao MIDL: "moi tham so trong interface nay
// deu la kieu Automation-compatible (BSTR, VARIANT, long...)" -> Windows
// dung duoc UNIVERSAL MARSHALER co san trong oleaut32.dll de marshal
// qua mang, KHONG can tu build proxy/stub DLL rieng (khac voi custom
// interface thuong, bat buoc phai compile SayHello_p.c thanh 1 DLL rieng).
//
// Bien dich:
//   midl SayHello.idl
//
// Sinh ra:
//   SayHello.h     - khai bao ISayHello (vtable) de include vao .cpp
//   SayHello_i.c   - dinh nghia that cua CLSID/IID/LIBID (phai link file nay)
//   SayHello.tlb   - type library nhi phan, can de RegisterTypeLib() doc

import "oaidl.idl";
import "ocidl.idl";

[
    object,
    uuid(11112222-3333-4444-5555-666677778888),
    oleautomation,
    pointer_default(unique)
]
interface ISayHello : IUnknown
{
    // [in] name: du lieu client gui vao
    // [out, retval] greeting: du lieu server tra ve, dong vai tro gia tri
    //                          tra ve cua ham (giong "return" thay vi
    //                          tham so con tro binh thuong)
    HRESULT SayHello([in] BSTR name, [out, retval] BSTR* greeting);
}

[
    uuid(99998888-7777-6666-5555-444433332222),
    version(1.0)
]
library SayHelloLib
{
    importlib("stdole2.tlb");

    [
        uuid(aaaa1111-2222-3333-4444-555566667777)
    ]
    coclass SayHelloServer
    {
        [default] interface ISayHello;
    };
};
